---
port: 8080
ServerHost: localhost
BASE_URL:   "http://localhost:8080"
SERVER_ADDRESS:  "localhost:8080"
FILE_STORAGE_PATH: "/tmp/test"
DATABASE_DSN: "postgres://postgres:boris123@localhost:5432/praktikum?sslmode=disable"
TRUSTED_SUBNET: "127.0.0.0/24"
SERVER_GRPC: "localhost:3200"